[package]
name = "rust-pathtracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.31.0"
nalgebra-glm = "0.17.0"
rayon = "1.5.3"
rand = "0.8.5"
